---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-http-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-http-app
    spec:
      containers:
      - name: nginx-container
        image: kwashizaki/example-vue-cli:v1.0.0
        ports:
        - name: http-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    app: sample-http-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http-port
  selector:
    app: sample-http-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
spec:
  rules:
  # VirtualHostのホスト名
  - host: localhost
    http:
      paths:
      # {DocumentRoot}/app1がトップディレクトリになる
      - path: /
        backend:
          # bindするService名
          # service.yamlのmetadata.nameと合わせる
          serviceName: http-service
          # Serviceが公開しているPort
          servicePort: 80
